@api_dotnet_HostAddress = https://localhost:7257


GET {{api_dotnet_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{api_dotnet_HostAddress}}/weatherforecast

###

GET {{api_dotnet_HostAddress}}/api/book

###
